import type {
  RetailRegressionCategory,
  RetailRegressionExpectation,
} from "@/lib/retail-regression";

type ScenarioGroup = {
  key: string;
  title: string;
  category: RetailRegressionCategory;
  tags: string[];
  openings: [string, string, string, string, string];
  followups?: string[];
  expectations: RetailRegressionExpectation;
};

const PRODUCT_TOOL = "searchSuperValuProducts";

const groups: ScenarioGroup[] = [
  {
    key: "wine-gums-offer",
    title: "Wine gums stay in confectionery for offers",
    category: "edge_cases",
    tags: ["offers", "collision", "wine-gums"],
    openings: [
      "Any wine gums on offer?",
      "Hiya, are the wine gums on special this week?",
      "What deals have ye on wine gums?",
      "Wine gums offers?",
      "Yeah just wondering if Maynards wine gums are on offer.",
    ],
    expectations: {
      summary: "Search wine gums as a grocery/confectionery product, never as alcohol.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustInclude: ["wine", "gums"],
      forbiddenServiceAreas: ["off_licence", "off licence", "alcohol"],
    },
  },
  {
    key: "wine-gums-stock",
    title: "Wine gums stock question is not alcohol",
    category: "stock",
    tags: ["stock", "collision", "wine-gums"],
    openings: [
      "Do ye stock wine gums?",
      "Have you Maynards wine gums in the shop?",
      "Any wine gums there?",
      "Hi, would you have wine gums?",
      "Are wine gums something ye normally carry?",
    ],
    expectations: {
      summary: "Treat wine gums as a product stock/range question, not off-licence.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "stock",
      queryMustInclude: ["wine", "gums"],
      forbiddenServiceAreas: ["off_licence", "off licence", "alcohol"],
      assistantMustNotInclude: [
        "we definitely have",
        "definitely in stock",
        "guaranteed in stock",
        "we stock it",
        "we carry it",
      ],
    },
  },
  {
    key: "cider-vinegar-crisps",
    title: "Cider vinegar crisps do not route to alcohol",
    category: "edge_cases",
    tags: ["offers", "collision", "crisps"],
    openings: [
      "Any cider vinegar crisps on offer?",
      "Salt and cider vinegar crisps, any deals?",
      "Have ye offers on cider vinegar crisps?",
      "Cider vinegar crisps special?",
      "Hiya, what's the offer on cider vinegar crisps if there is one?",
    ],
    expectations: {
      summary: "Keep the complete crisp product identity and never infer off-licence from cider.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustIncludeAny: ["cider vinegar", "crisps"],
      forbiddenServiceAreas: ["off_licence", "off licence", "alcohol"],
    },
  },
  {
    key: "apple-cider-vinegar",
    title: "Apple cider vinegar price is not alcohol",
    category: "prices",
    tags: ["price", "collision", "vinegar"],
    openings: [
      "How much is apple cider vinegar?",
      "What's the price of apple cider vinegar?",
      "Apple cider vinegar price please.",
      "Hi, what are ye charging for cider vinegar?",
      "How much for a bottle of apple cider vinegar?",
    ],
    expectations: {
      summary: "Search apple cider vinegar as a grocery product and preserve vinegar in the query.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "price",
      queryMustIncludeAny: ["cider vinegar", "vinegar"],
      forbiddenServiceAreas: ["off_licence", "off licence", "alcohol"],
    },
  },
  {
    key: "beer-battered-cod",
    title: "Beer battered food does not route to off-licence",
    category: "edge_cases",
    tags: ["offers", "collision", "frozen"],
    openings: [
      "Any beer battered cod on offer?",
      "Have ye beer battered fish on special?",
      "Beer battered cod deals?",
      "Hiya, is the beer battered fish reduced?",
      "What's on offer for beer battered cod?",
    ],
    expectations: {
      summary: "Treat beer-battered cod as a food product; beer must not force alcohol routing.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustIncludeAny: ["beer battered", "cod", "fish"],
      forbiddenServiceAreas: ["off_licence", "off licence", "alcohol"],
    },
  },
  {
    key: "birds-eye-fish-fingers",
    title: "Birds Eye fish fingers preserve brand and product",
    category: "offers",
    tags: ["offers", "brand", "frozen"],
    openings: [
      "Are Birds Eye fish fingers on offer?",
      "Any deals on Birds Eye fish fingers?",
      "Birds Eye fish fingers special this week?",
      "Hiya, what offers have ye on Birds Eye fish fingers?",
      "Have you any Birds Eye fish finger deals?",
    ],
    expectations: {
      summary: "Search the full Birds Eye fish-finger identity rather than browsing the fish counter.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustInclude: ["birds", "eye"],
      queryMustIncludeAny: ["fish fingers", "fish finger"],
      forbiddenServiceAreas: ["fish_counter", "fish counter"],
    },
  },
  {
    key: "squares-bars-price",
    title: "Squares bars price keeps product identity",
    category: "prices",
    tags: ["price", "brand", "snacks"],
    openings: [
      "How much are Squares bars?",
      "What's the price of Squares bars?",
      "Squares cereal bars price?",
      "Hi, how much for the Squares bars?",
      "What are those Squares bars going for?",
    ],
    expectations: {
      summary: "Search Squares bars as a specific product instead of a broad snack/category browse.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "price",
      queryMustInclude: ["squares"],
    },
  },
  {
    key: "dairy-milk-offer",
    title: "Cadbury Dairy Milk stays a specific product",
    category: "offers",
    tags: ["offers", "brand", "chocolate"],
    openings: [
      "Any Cadbury Dairy Milk on offer?",
      "Is Dairy Milk on special?",
      "Cadbury Dairy Milk deals this week?",
      "Hiya, what offers are on Dairy Milk?",
      "Have ye Cadbury Dairy Milk reduced?",
    ],
    expectations: {
      summary: "Search Dairy Milk as a specific chocolate product, not a dairy-wall browse.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustIncludeAny: ["dairy milk", "cadbury"],
      forbiddenServiceAreas: ["dairy", "dairy_wall", "dairy wall"],
    },
  },
  {
    key: "avocado-price",
    title: "Fresh avocado price search",
    category: "prices",
    tags: ["price", "produce", "clarification"],
    openings: [
      "How much are the fresh avocados?",
      "What's the cheapest fresh avocado?",
      "Price of a fresh avocado please.",
      "Hiya, how much is your cheapest avocado?",
      "What are ye charging for fresh avocados?",
    ],
    expectations: {
      summary: "Search fresh avocado pricing rather than avocado oil or unrelated products.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "price",
      queryMustIncludeAny: ["avocado", "avocados"],
    },
  },
  {
    key: "weetabix-stock",
    title: "Weetabix stock/range query",
    category: "stock",
    tags: ["stock", "cereal"],
    openings: [
      "Do ye stock Weetabix?",
      "Have you Weetabix?",
      "Would you normally carry Weetabix?",
      "Hi, is Weetabix something ye sell?",
      "Any Weetabix in the range?",
    ],
    expectations: {
      summary: "Use a stock/range lookup for Weetabix without claiming live shelf inventory.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "stock",
      queryMustInclude: ["weetabix"],
      assistantMustNotInclude: [
        "definitely on the shelf",
        "guaranteed in stock right now",
        "we stock it",
        "we carry it",
      ],
    },
  },
  {
    key: "gluten-free-bread-stock",
    title: "Gluten-free bread range query",
    category: "stock",
    tags: ["stock", "bread", "dietary"],
    openings: [
      "Do ye have gluten free bread?",
      "Any gluten-free bread there?",
      "Would you stock gluten free bread?",
      "Hiya, have you any gluten free loaves?",
      "Do you carry gluten-free bread?",
    ],
    expectations: {
      summary: "Search the product range for gluten-free bread and avoid a live-stock guarantee.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "stock",
      queryMustIncludeAny: ["gluten free", "gluten-free"],
      assistantMustNotInclude: [
        "definitely on the shelf",
        "guaranteed in stock right now",
        "we stock it",
        "we carry it",
      ],
    },
  },
  {
    key: "baby-formula-stock",
    title: "Baby formula range query",
    category: "stock",
    tags: ["stock", "baby"],
    openings: [
      "Do ye stock baby formula?",
      "Have you any baby formula?",
      "Would you carry infant formula?",
      "Hi, is baby formula in your range?",
      "Any formula for babies there?",
    ],
    expectations: {
      summary: "Use the product stock/range path for baby formula.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "stock",
      queryMustIncludeAny: ["formula", "baby", "infant"],
      assistantMustNotInclude: [
        "we definitely have",
        "definitely in stock",
        "we stock it",
        "we carry it",
      ],
    },
  },
  {
    key: "guinness-offer",
    title: "Guinness offers route to off-licence",
    category: "offers",
    tags: ["offers", "off-licence", "beer"],
    openings: [
      "Any Guinness on offer?",
      "What Guinness deals have ye?",
      "Guinness specials this week?",
      "Hiya, is there an offer on Guinness?",
      "Have you Guinness cans on special?",
    ],
    expectations: {
      summary: "Treat Guinness as an alcohol product offer, preserve Guinness in the query, and give the age reminder.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustInclude: ["guinness"],
      assistantMustIncludeAny: ["18", "eighteen"],
    },
  },
  {
    key: "wine-offer",
    title: "Genuine wine browse routes to off-licence",
    category: "departments",
    tags: ["offers", "off-licence", "browse"],
    openings: [
      "Any wine on offer?",
      "What wine deals have ye this week?",
      "Anything decent on special in the wine?",
      "Hi, what wines are on offer?",
      "Wine offers please.",
    ],
    expectations: {
      summary: "A genuine wine offer browse should use the off-licence scope.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      requiredServiceArea: "off_licence",
    },
  },
  {
    key: "sirloin-counter-offer",
    title: "Sirloin at the meat counter stays counter-specific",
    category: "departments",
    tags: ["offers", "butcher", "counter"],
    openings: [
      "Is sirloin on offer at the meat counter?",
      "Any sirloin deals at the butcher counter?",
      "What's the sirloin offer on the meat counter?",
      "Hiya, have ye sirloin on special at the counter?",
      "Any counter sirloin reduced this week?",
    ],
    expectations: {
      summary: "Search sirloin offers in the butcher/meat-counter scope.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustInclude: ["sirloin"],
      requiredServiceArea: "butcher",
      requiredFulfilment: "counter",
    },
  },
  {
    key: "steak-ambiguous",
    title: "Ambiguous steak offer asks counter or pre-pack",
    category: "clarification",
    tags: ["offers", "steak", "clarification"],
    openings: [
      "Any steaks on offer?",
      "What steak deals have ye?",
      "Steaks on special?",
      "Hiya, any offers on steak this week?",
      "Have you steak reduced?",
    ],
    expectations: {
      summary: "When fulfilment is genuinely ambiguous, ask whether they mean counter or pre-pack before narrowing.",
      mustAskClarifyingQuestion: true,
      noError: true,
    },
  },
  {
    key: "salmon-fish-counter",
    title: "Salmon at fish counter uses fish counter scope",
    category: "departments",
    tags: ["offers", "fish", "counter"],
    openings: [
      "Any salmon on offer at the fish counter?",
      "Fish counter salmon deals?",
      "What's the salmon offer at the fresh fish counter?",
      "Hi, have ye salmon on special at the fish counter?",
      "Any counter salmon reduced?",
    ],
    expectations: {
      summary: "Keep salmon within the fish-counter scope when the caller explicitly says counter.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustInclude: ["salmon"],
      requiredServiceArea: "fish",
      requiredFulfilment: "counter",
    },
  },
  {
    key: "butcher-counter-browse",
    title: "Butcher counter offer browse",
    category: "departments",
    tags: ["offers", "butcher", "browse"],
    openings: [
      "What's on offer at the butcher counter?",
      "Any meat counter specials?",
      "What deals have ye at the butchers?",
      "Hiya, what's reduced at the meat counter?",
      "Any offers on the fresh meat counter?",
    ],
    expectations: {
      summary: "Browse butcher-counter offers rather than pre-packed grocery meat.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      requiredServiceArea: "butcher",
      requiredFulfilment: "counter",
    },
  },
  {
    key: "produce-browse",
    title: "Fruit and veg offer browse",
    category: "departments",
    tags: ["offers", "produce", "browse"],
    openings: [
      "What's on offer in fruit and veg?",
      "Any fruit and veg specials?",
      "What produce deals have ye?",
      "Hiya, anything reduced in fruit and veg?",
      "Offers in the fruit and veg section?",
    ],
    expectations: {
      summary: "Browse produce offers using the produce scope.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      requiredServiceArea: "produce",
    },
  },
  {
    key: "three-for-ten-produce",
    title: "Three for a tenner in fruit and veg",
    category: "offers",
    tags: ["promotion", "multibuy", "produce"],
    openings: [
      "Anything three for a tenner in fruit and veg?",
      "What fruit and veg is 3 for 10 euro?",
      "Any three-for-ten deals in produce?",
      "Hiya, have ye a three for a tenner offer on fruit or veg?",
      "What's included in the 3 for €10 fruit and veg deal?",
    ],
    expectations: {
      summary: "Preserve the multibuy mechanic and produce scope.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      requiredServiceArea: "produce",
      queryMustIncludeAny: ["3 for", "three for", "tenner", "10"],
    },
  },
  {
    key: "half-price-shampoo",
    title: "Half-price shampoo promotion",
    category: "offers",
    tags: ["promotion", "half-price", "health-beauty"],
    openings: [
      "Any shampoo half price?",
      "What shampoos are half price?",
      "Half-price shampoo deals?",
      "Hi, have ye any shampoo at half price?",
      "Anything in shampoo reduced by half?",
    ],
    expectations: {
      summary: "Search shampoo offers while preserving the half-price mechanic.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustInclude: ["shampoo"],
    },
  },
  {
    key: "rewards-250",
    title: "Rewards Price €2.50 browse",
    category: "offers",
    tags: ["promotion", "rewards"],
    openings: [
      "What's on Rewards Price for €2.50?",
      "Anything with Rewards at two fifty?",
      "What offers are €2.50 with Real Rewards?",
      "Hiya, show me the Rewards deals at 2.50.",
      "Any Real Rewards offers for two euro fifty?",
    ],
    expectations: {
      summary: "Preserve Rewards-price semantics and the €2.50 amount.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustIncludeAny: ["rewards", "2.50", "two fifty", "two euro fifty"],
    },
  },
  {
    key: "save-50c-detergent",
    title: "Save 50c detergent promotion",
    category: "offers",
    tags: ["promotion", "save-amount", "household"],
    openings: [
      "Any detergent where you save 50 cent?",
      "What washing detergent has 50c off?",
      "Save fifty cent on detergent, anything there?",
      "Hi, any laundry detergent reduced by 50 cent?",
      "Which detergent has fifty cents off?",
    ],
    expectations: {
      summary: "Search detergent offers while retaining the save-50c mechanic.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustIncludeAny: ["detergent", "laundry"],
    },
  },
  {
    key: "toilet-roll-price",
    title: "Toilet roll price lookup",
    category: "prices",
    tags: ["price", "household"],
    openings: [
      "How much is toilet roll?",
      "What's the price of toilet paper?",
      "Toilet roll price please.",
      "Hiya, what are ye charging for toilet rolls?",
      "Any price on kitchen—sorry, toilet roll?",
    ],
    expectations: {
      summary: "Use a product price lookup for toilet roll/paper.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "price",
      queryMustIncludeAny: ["toilet", "paper"],
    },
  },
  {
    key: "cereal-offer",
    title: "Cereal offer browse",
    category: "offers",
    tags: ["offers", "cereal"],
    openings: [
      "Any cereal on offer?",
      "What cereal deals have ye?",
      "Cereal specials this week?",
      "Hiya, anything reduced in cereal?",
      "What's on offer for breakfast cereal?",
    ],
    expectations: {
      summary: "Use an offer search for cereal.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustIncludeAny: ["cereal", "breakfast"],
    },
  },
  {
    key: "laptop-stock",
    title: "Unusual product request fails safely",
    category: "edge_cases",
    tags: ["stock", "unusual", "no-hallucination"],
    openings: [
      "Do ye sell laptops?",
      "Any laptops in the shop?",
      "Would SuperValu have a laptop?",
      "Hi, do you stock laptop computers?",
      "Can I buy a laptop there?",
    ],
    expectations: {
      summary: "Search safely and do not invent a laptop range or live stock.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "stock",
      queryMustInclude: ["laptop"],
      assistantMustNotInclude: ["yes, we definitely", "definitely in stock", "guaranteed in stock"],
    },
  },
  {
    key: "opening-hours",
    title: "Opening-hours question does not search products",
    category: "knowledge",
    tags: ["hours", "store-info"],
    openings: [
      "What time do ye close?",
      "What are your opening hours today?",
      "Hiya, when does the shop shut?",
      "Are ye open late tonight?",
      "What time are you open until?",
    ],
    expectations: {
      summary: "Answer from store knowledge; never use the product catalogue tool.",
      forbiddenTools: [PRODUCT_TOOL],
      noError: true,
    },
  },
  {
    key: "parking",
    title: "Parking question does not search products",
    category: "knowledge",
    tags: ["parking", "store-info"],
    openings: [
      "Is there parking there?",
      "Have ye a car park?",
      "Where do I park for the shop?",
      "Hiya, is parking available?",
      "Can I park outside the store?",
    ],
    expectations: {
      summary: "Answer parking from store knowledge or safely say it is not known; never product-search.",
      forbiddenTools: [PRODUCT_TOOL],
      noError: true,
    },
  },
  {
    key: "click-collect",
    title: "Click and collect question does not search products",
    category: "knowledge",
    tags: ["click-collect", "store-info"],
    openings: [
      "Do ye do click and collect?",
      "Can I order online and collect?",
      "Is click & collect available?",
      "Hi, have you click and collect there?",
      "Can I collect an online grocery order from the shop?",
    ],
    expectations: {
      summary: "Use approved store knowledge for click-and-collect; do not route into product search.",
      forbiddenTools: [PRODUCT_TOOL],
      noError: true,
    },
  },
  {
    key: "cereal-to-weetabix",
    title: "Follow-up changes broad cereal offer into Weetabix stock",
    category: "multi_turn",
    tags: ["context", "stock", "intent-switch"],
    openings: [
      "Any cereal on offer?",
      "Hiya, what cereal deals have ye?",
      "Anything reduced in cereal?",
      "Cereal offers?",
      "What breakfast cereals are on special?",
    ],
    followups: ["Actually forget the offers, do ye normally stock Weetabix?"],
    expectations: {
      summary: "The latest explicit stock question must override earlier offer context.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "stock",
      queryMustInclude: ["weetabix"],
    },
  },
  {
    key: "avocado-refinement",
    title: "Avocado follow-up narrows to fresh cheapest product",
    category: "multi_turn",
    tags: ["context", "price", "clarification"],
    openings: [
      "How much are avocados?",
      "Avocado price?",
      "What price is avocado?",
      "Hiya, how much for avocado?",
      "Can you tell me the price of an avocado?",
    ],
    followups: ["Fresh ones, cheapest SuperValu one if there is one."],
    expectations: {
      summary: "Keep avocado context, honor the explicit cheapest selection, and do not ask another type/brand question.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "price",
      queryMustIncludeAny: ["avocado", "avocados"],
      lastTurnMustNotAskClarifyingQuestion: true,
    },
  },
  {
    key: "steak-counter-refinement",
    title: "Steak follow-up selects the meat counter",
    category: "multi_turn",
    tags: ["context", "offers", "butcher"],
    openings: [
      "Any steaks on offer?",
      "What steak deals have ye?",
      "Steaks on special?",
      "Hiya, anything on offer in steak?",
      "Have ye any steak deals?",
    ],
    followups: ["The fresh meat counter, not the pre-packed ones."],
    expectations: {
      summary: "After the caller specifies the fresh meat counter, search counter steak offers.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustIncludeAny: ["steak", "steaks"],
      requiredServiceArea: "butcher",
      requiredFulfilment: "counter",
    },
  },
  {
    key: "wine-gums-intent-switch",
    title: "Wine gums follow-up switches offer to stock",
    category: "multi_turn",
    tags: ["context", "intent-switch", "wine-gums"],
    openings: [
      "Any wine gums on offer?",
      "Are wine gums on special?",
      "Wine gum deals?",
      "Hiya, any offers on Maynards wine gums?",
      "What deals are on wine gums?",
    ],
    followups: ["Actually never mind the offer — do ye normally stock them?"],
    expectations: {
      summary: "Newest stock intent must override offer context while wine gums remain non-alcohol.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "stock",
      queryMustInclude: ["wine", "gums"],
      forbiddenServiceAreas: ["off_licence", "off licence", "alcohol"],
    },
  },
  {
    key: "fish-fingers-brand-refinement",
    title: "Fish fingers follow-up preserves Birds Eye brand",
    category: "multi_turn",
    tags: ["context", "brand", "offers"],
    openings: [
      "Any fish fingers on offer?",
      "What fish finger deals have ye?",
      "Fish fingers on special?",
      "Hiya, anything reduced in fish fingers?",
      "Have you offers on fish fingers?",
    ],
    followups: ["Birds Eye ones specifically."],
    expectations: {
      summary: "Refine the existing fish-finger offer request to Birds Eye without routing to fresh fish.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustInclude: ["birds", "eye"],
      queryMustIncludeAny: ["fish finger", "fish fingers"],
      forbiddenServiceAreas: ["fish_counter", "fish counter"],
    },
  },
  {
    key: "wine-aisle-explicit",
    title: "Explicit wine aisle browse stays off-licence",
    category: "departments",
    tags: ["off-licence", "browse", "explicit-area"],
    openings: [
      "What's on offer in the wine aisle?",
      "Any deals in the wine aisle?",
      "Wine aisle specials?",
      "Hiya, anything reduced down the wine aisle?",
      "What offers have ye in the wine section?",
    ],
    expectations: {
      summary: "Explicit wine aisle wording is a genuine off-licence browse.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      requiredServiceArea: "off_licence",
    },
  },
  {
    key: "dairy-wall-browse",
    title: "Explicit dairy wall browse stays department-scoped",
    category: "departments",
    tags: ["dairy", "browse", "explicit-area"],
    openings: [
      "What's on offer on the dairy wall?",
      "Any dairy wall specials?",
      "What deals have ye in the dairy section?",
      "Hiya, anything reduced on the dairy wall?",
      "Dairy section offers please.",
    ],
    expectations: {
      summary: "Explicit dairy-area wording should remain a grocery dairy-section browse.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      requiredServiceArea: "grocery",
    },
  },
  {
    key: "mixed-shopping-list",
    title: "Mixed shopping list stays broad rather than one product",
    category: "edge_cases",
    tags: ["browse", "multi-category"],
    openings: [
      "Any offers on milk bread crisps chocolate and fruit?",
      "What's on special for milk, bread, crisps, chocolate and fruit?",
      "Deals on milk bread crisps chocolate fruit?",
      "Hiya, anything reduced across milk bread crisps chocolate and fruit?",
      "Could you tell me offers for milk, bread, crisps, chocolate and fruit?",
    ],
    expectations: {
      summary: "Recognise a genuine multi-category browse instead of collapsing it into one accidental product.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustIncludeAny: ["milk", "bread", "crisps", "chocolate", "fruit"],
    },
  },
  {
    key: "four-word-product",
    title: "Four-word product phrase is still a product",
    category: "edge_cases",
    tags: ["specific-product", "routing"],
    openings: [
      "Any chocolate digestive biscuits on offer?",
      "Chocolate digestive biscuits deals?",
      "Are milk chocolate digestive biscuits reduced?",
      "Hiya, what offers are on chocolate digestive biscuits?",
      "Have ye chocolate digestive biscuits on special?",
    ],
    expectations: {
      summary: "Do not treat a four-word product identity as a broad shopping-list browse.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustIncludeAny: ["digestive", "biscuits"],
    },
  },
  {
    key: "typo-avocado",
    title: "Light transcription error still finds avocado",
    category: "edge_cases",
    tags: ["stt-like", "price", "typo"],
    openings: [
      "How much is an avacado?",
      "Avocardo price please.",
      "What price are the avacados?",
      "Hiya, how much for an avacado?",
      "Cheapest avocardo you've got?",
    ],
    expectations: {
      summary: "Recover from a plausible avocado transcription/spelling error, keep price intent, and do not give up on the misspelling.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "price",
      queryMustIncludeAny: ["avocado", "avacado", "avocardo"],
      assistantMustNotInclude: [
        "couldn't find the price",
        "can't see the price",
        "could not find the price",
      ],
    },
  },
  {
    key: "casual-irish-offer",
    title: "Casual Irish phrasing keeps offer intent",
    category: "openings",
    tags: ["irish-phrasing", "offers", "casual"],
    openings: [
      "Any chance ye have tea bags on offer there?",
      "Here, would there be any deals on tea bags?",
      "What's the craic with tea bag offers?",
      "Hiya, have ye anything going on tea bags?",
      "Do ye know are tea bags on special at all?",
    ],
    expectations: {
      summary: "Understand casual caller wording as an offer search for tea bags.",
      requiredTool: PRODUCT_TOOL,
      requiredIntent: "offer",
      queryMustIncludeAny: ["tea", "tea bags"],
    },
  },
];

export type BuiltInRetailRegressionScenario = {
  slug: string;
  title: string;
  category: RetailRegressionCategory;
  tags: string[];
  turns: Array<{ caller: string }>;
  expectations: RetailRegressionExpectation;
  source: "built_in";
  active: true;
};

export function buildDefaultRetailRegressionScenarios(): BuiltInRetailRegressionScenario[] {
  const scenarios = groups.flatMap((group) =>
    group.openings.map((opening, index) => ({
      slug: `${group.key}-${String(index + 1).padStart(2, "0")}`,
      title: `${group.title} · ${index + 1}`,
      category: group.category,
      tags: group.tags,
      turns: [
        { caller: opening },
        ...(group.followups ?? []).map((caller) => ({ caller })),
      ],
      expectations: group.expectations,
      source: "built_in" as const,
      active: true as const,
    })),
  );

  if (scenarios.length !== 200) {
    throw new Error(`Retail regression library must contain 200 scenarios; found ${scenarios.length}.`);
  }

  return scenarios;
}
