/**
 * Create or update `.env.local` from the hosted Supabase project.
 *
 * Requires a Supabase personal access token:
 *   - `supabase login` (writes ~/.supabase/access-token), or
 *   - SUPABASE_ACCESS_TOKEN in the environment / .env.local
 *
 * Run:
 *   npx tsx scripts/bootstrap-env-local.ts
 */

import { randomBytes } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const PROJECT_REF = "rtoebbwzwxcnscsxghww";
const ENV_LOCAL = join(process.cwd(), ".env.local");

type ApiKeyRow = {
  name?: string;
  type?: string;
  api_key?: string | null;
};

async function readAccessToken(): Promise<string> {
  if (process.env.SUPABASE_ACCESS_TOKEN?.trim()) {
    return process.env.SUPABASE_ACCESS_TOKEN.trim();
  }

  const os = await import("node:os");
  const path = await import("node:path");
  const fs = await import("node:fs/promises");

  const cliTokenPath = path.join(os.homedir(), ".supabase", "access-token");
  try {
    const cliToken = (await fs.readFile(cliTokenPath, "utf8")).trim();
    if (cliToken) return cliToken;
  } catch {
    // fall through
  }

  try {
    const envLocal = await fs.readFile(ENV_LOCAL, "utf8");
    const match = envLocal.match(/^SUPABASE_ACCESS_TOKEN=(.+)$/m);
    if (match?.[1]?.trim()) {
      return match[1].trim().replace(/^["']|["']$/g, "");
    }
  } catch {
    // fall through
  }

  throw new Error(
    "No Supabase access token. Run `supabase login` or set SUPABASE_ACCESS_TOKEN.",
  );
}

async function managementFetch<T>(
  token: string,
  path: string,
): Promise<T> {
  const response = await fetch(`https://api.supabase.com/v1${path}`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  const text = await response.text();
  if (!response.ok) {
    throw new Error(
      `Management API GET ${path} failed (${response.status}): ${text.slice(0, 400)}`,
    );
  }
  return text ? (JSON.parse(text) as T) : ({} as T);
}

function pickKey(rows: ApiKeyRow[], names: string[]): string | null {
  for (const name of names) {
    const row = rows.find(
      (r) => r.name === name || r.type === name,
    );
    if (row?.api_key?.trim()) return row.api_key.trim();
  }
  return null;
}

function parseEnv(content: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    map.set(trimmed.slice(0, eq), trimmed.slice(eq + 1));
  }
  return map;
}

function renderEnv(map: Map<string, string>): string {
  const order = [
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY",
    "SUPABASE_SERVICE_ROLE_KEY",
    "CLISTE_ADMIN_SECRET",
    "SUPABASE_ACCESS_TOKEN",
  ];
  const lines = [
    "# Generated by scripts/bootstrap-env-local.ts — do not commit.",
    "",
  ];
  const written = new Set<string>();
  for (const key of order) {
    const value = map.get(key);
    if (value == null) continue;
    lines.push(`${key}=${value}`);
    written.add(key);
  }
  for (const [key, value] of map.entries()) {
    if (written.has(key)) continue;
    lines.push(`${key}=${value}`);
  }
  lines.push("");
  return lines.join("\n");
}

async function main() {
  const token = await readAccessToken();
  const projects = await managementFetch<
    Array<{ id: string; name: string; ref: string; region: string }>
  >(token, "/projects");

  let projectRef = PROJECT_REF;
  const listed = projects.find((p) => p.ref === PROJECT_REF);
  if (!listed) {
    const cliste = projects.find((p) =>
      /cliste/i.test(p.name) || /cliste/i.test(p.ref),
    );
    if (cliste) {
      projectRef = cliste.ref;
      console.warn(
        `Project ref ${PROJECT_REF} not found in your account; using ${projectRef} (${cliste.name}).`,
      );
    } else {
      throw new Error(
        `Project ${PROJECT_REF} not found. Available: ${projects.map((p) => p.ref).join(", ") || "(none)"}`,
      );
    }
  }

  const keys = await managementFetch<ApiKeyRow[]>(
    token,
    `/projects/${projectRef}/api-keys?reveal=true`,
  );

  const anonKey =
    pickKey(keys, ["anon", "publishable"]) ??
    pickKey(keys, ["default", "publishable"]);
  const serviceRoleKey =
    pickKey(keys, ["service_role", "secret"]) ??
    pickKey(keys, ["default", "secret"]);

  if (!anonKey || !serviceRoleKey) {
    throw new Error(
      "Could not resolve anon/publishable and service_role/secret keys from Management API.",
    );
  }

  const supabaseUrl = `https://${projectRef}.supabase.co`;

  let existing = new Map<string, string>();
  try {
    existing = parseEnv(await readFile(ENV_LOCAL, "utf8"));
  } catch {
    // new file
  }

  existing.set("NEXT_PUBLIC_SUPABASE_URL", supabaseUrl);
  existing.set("NEXT_PUBLIC_SUPABASE_ANON_KEY", anonKey);
  existing.set("SUPABASE_SERVICE_ROLE_KEY", serviceRoleKey);
  if (!existing.get("CLISTE_ADMIN_SECRET")?.trim()) {
    existing.set(
      "CLISTE_ADMIN_SECRET",
      randomBytes(24).toString("base64url"),
    );
  }
  if (!existing.has("SUPABASE_ACCESS_TOKEN")) {
    existing.set("SUPABASE_ACCESS_TOKEN", token);
  }

  await writeFile(ENV_LOCAL, renderEnv(existing), "utf8");

  console.log("Wrote .env.local:");
  console.log(`  NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}`);
  console.log("  NEXT_PUBLIC_SUPABASE_ANON_KEY=***");
  console.log("  SUPABASE_SERVICE_ROLE_KEY=***");
  console.log("  CLISTE_ADMIN_SECRET=***");
  console.log("");
  console.log("Restart the dev server: npm run dev");
  console.log("Patch auth redirect URLs: npx tsx scripts/patch-supabase-auth-urls.ts");
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
